input {
  beats {
    port => 5045
  }
}

filter {
  if [@metadata][beat] == "metricbeat" {
    mutate {
      add_field => { "source_type" => "system_metrics" }
    }
  } else if [@metadata][beat] == "packetbeat" {
    mutate {
      add_field => { "source_type" => "network_traffic" }
    }
  }
}

output {
  if [@metadata][beat] == "filebeat" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "filebeat-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
  } else if [@metadata][beat] == "metricbeat" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "metricbeat-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
  } else if [@metadata][beat] == "packetbeat" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "packetbeat-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
  }
}
